### ISSUE TITLE
No module named 'rust_ac.rust_ac'

### ISSUE THREAD

**Issue by guojiahuiEmily** [AI-Arena/rust-arenaclient#22]
dear,
how to solve this problem:

  File "gfgo.py", line 2, in <module>
    from rust_ac import Server
  File "/Volumes/MACDATA/Down/rust-arenaclient-master/rust_ac/__init__.py", line 1, in <module>
    from .rust_ac import PServer
ModuleNotFoundError: No module named 'rust_ac.rust_ac'

**Comment by danielvschoor** [comment]
Either build this repo with rust + maturin, or simply:
pip install rust-arenaclient

**Comment by guojiahuiEmily** [comment]
Still error.

(venv) FengdeMacBook-Pro-3:rust-arenaclient-master fengguo$ pip install rust_arenaclient
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: rust_arenaclient in ./venv/lib/python3.7/site-packages (0.1.15)
Requirement already satisfied: portpicker in ./venv/lib/python3.7/site-packages (from rust_arenaclient) (1.3.1)
Requirement already satisfied: aiohttp in ./venv/lib/python3.7/site-packages (from rust_arenaclient) (3.6.3)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./venv/lib/python3.7/site-packages (from aiohttp->rust_arenaclient) (3.0.1)
Requirement already satisfied: chardet<4.0,>=2.0 in ./venv/lib/python3.7/site-packages (from aiohttp->rust_arenaclient) (3.0.4)
Requirement already satisfied: yarl<1.6.0,>=1.0 in ./venv/lib/python3.7/site-packages (from aiohttp->rust_arenaclient) (1.5.1)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.7/site-packages (from aiohttp->rust_arenaclient) (20.3.0)
Requirement already satisfied: multidict<5.0,>=4.5 in ./venv/lib/python3.7/site-packages (from aiohttp->rust_arenaclient) (4.7.6)
Requirement already satisfied: typing-extensions>=3.7.4 in ./venv/lib/python3.7/site-packages (from yarl<1.6.0,>=1.0->aiohttp->rust_arenaclient) (3.7.4.3)
Requirement already satisfied: idna>=2.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from yarl<1.6.0,>=1.0->aiohttp->rust_arenaclient) (2.10)
(venv) FengdeMacBook-Pro-3:rust-arenaclient-master fengguo$ python gfgo.py 
Traceback (most recent call last):
  File "gfgo.py", line 2, in <module>
    from rust_ac import Server
  File "/Volumes/MACDATA/Down/rust-arenaclient-master/rust_ac/__init__.py", line 1, in <module>
    from .rust_ac import PServer
ModuleNotFoundError: No module named 'rust_ac.rust_ac'

**Comment by guojiahuiEmily** [comment]
would u please attach rust_ac.rust_ac.py in here

**Comment by LostLucidity** [comment]
Hi @guojiahuiEmily. There's an active discord that you can ask your questions for more visibility if you're interested.
[AI Arena discord](https://discord.gg/XKH92gHa)
